### ISSUE TITLE
npm WARN when after "npm link"

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-cli#105]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description
After executing "npm link" the CLI shows a warning:
```
npm WARN The package @types/ssh2 is included as both a dev and production dependency.
```

* npm -v => 5.3.0
* node -v => v8.4.0
* OS: MacOS Sierra 10.12.6

**Comment by ppathan** [comment]
This issues is fixed and there is no longer a requirement to do ```npm link```
