### ISSUE TITLE
CLI tool should tell if the user has sufficient permissions to deploy

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-cli#125]
# Type of issue
- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description
It would be nice if the CLI automatically, or with an option, could check whether the user has sufficient permissions to deploy the solution. For example, it could be a deployment step before creating any resource. One would also be allowed to skip the step to save time.

**Comment by ppathan** [comment]
This will be fixed with move to CIQS platform.
