### ISSUE TITLE
Improve "Deployed recources x of N" progress counter

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-cli#142]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
Due to implementation details, during the deployment the CLI shows "5 of 7" then "6 of 8"... then "7 of 11", "10 of 13" etc.  The issue is very visible and happens within seconds from the start, so it will lead to some confusion or "funny" comments :-)

We should find a way to improve the user experience, for example providing a better estimation to start with, or perhaps not showing the number. I assume that for each template we know before hand the approximate number of resources, it doesn't matter if it's exact, but rather than starting with "5 of 7" it could start with "5 of 13", and leave eventual corrections late in the installation process.

**Comment by ppathan** [comment]
This is fixed
