### ISSUE TITLE
CLI fails with 443

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-cli#159]
# Type of issue

- [ x] Bug
- [ ] New feature
- [ ] Improvement

# Description
Basic, dotnet deployment from CLI command line after npm start, npm build:

C:\source\PCS2\pcs-cli>pcs
? Enter a solution name: timbasic41
? Select a subscription: IoT Preconfigured Solutions - Engineering
? Select a location: East US
? Enter prefix for .azurewebsites.net: timbasic41
? Enter a user name for the virtual machine: timlav
? Enter a password for the virtual machine: ************
? Confirm your password: ************
✕ Error: Long running operation failed with error: "getaddrinfo ENOTFOUND management.azure.com management.azure.com:443".

Transient issue?  I've never seen this before (across ~100 deployments)

**Comment by vitoc** [comment]
Does indeed look like a transient issue with the underlying domain name resolution service not within the scope of the application, though the application can proactively retry for a while to ride it over if possible but that seems a bit over the top.

Slightly unrelated but good to also counter-check transient ARM deployment errors here: https://azure.microsoft.com/en-us/status/ at time of occurrence. Just in case you encountered the  extremely remote possibility that there's something going on with ARM.

**Comment by kalyanb9119** [comment]
I got the same issue again.. 

```{ Error: getaddrinfo ENOTFOUND management.azure.com management.azure.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'management.azure.com',
  host: 'management.azure.com',
  port: 443 }```
