### ISSUE TITLE
"time taken" doesn't seem to include all the steps

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-cli#170]
# Type of issue

- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description
The time taken shown after a deployment seems to be missing some of the time spent. e.g. this is one deployment, notice that 9'37" passed from when I launched the script and when I got the prompt back, but the script measured 7'44"

![31190972-868ac974-a8f1-11e7-882f-9756758eddb3](https://user-images.githubusercontent.com/371009/31487333-21dd39a4-aeef-11e7-88c9-0edf0e0d7f92.png)

**Comment by vitoc** [comment]
Yes, the time taken shown after a successful deployment is measured from the point after app registration and resource group creation and hence, does not consider the time taken for those activities. I'd added a separate time indicator for those in PR #180. Hope it helps. Also, added elapsed time counter in PR #179. There are also activities after the resource provisioning time taken is shown (and may need measurement too if desirable?). Just curious, what did you use to get the 9'37" measurement?

**Comment by ppathan** [comment]
Initially the focus was on knowing how much time resource provisioning is taking through ARM, so we added the time take for that purpose. Since then we have added several more steps to the solution deployment process so showing all up time makes more sense now. We will have to be careful how we surface this to the user.

**Comment by dluc** [comment]
@vitoc 9'37" (if my math is correct) is the difference between the two timestamps in the screenshot. My bash shell is configured to print the time after each command to help with these tasks ;-)

**Comment by vitoc** [comment]
Ah, very cool. That includes time taken for user input too, which pcs-cli currently doesn't measure (rightly). Anyway, on the other discussions related to this topic, I agree that resource provisioning time for each resource can be useful.

**Comment by dluc** [comment]
yes it includes about 20 sec of user input, what's missing is about 1.5 mins of time
