### ISSUE TITLE
The CLI should use "1.0.0-preview" by default and allow to deploy a different version, including "testing"

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-cli#172]
# Type of issue

- [ ] Bug
- [x] New feature
- [ ] Improvement

# Description

By default the CLI should deploy the latest stable version, allowing to select a different version, including the one under development.

When this is done, we should also update DockerCompose and Kubernetes template files in the repository to point to the latest stable version.

Note that different microservices might have different versions, so the version here is the version of the solution, not the version of the microservices. i.e. RM v2.0.5 might be using DeviceSimulation v1.0.8. The version that the user will pass is "2.0.5"

e.g.

Deploy latest version:
`pcs -t remotemonitoring -r dotnet`

Deploy a specific version, including testing:
`pcs -t remotemonitoring -r dotnet --release testing`
`pcs -t remotemonitoring -r dotnet --release 1.0.0-preview`
`pcs -t remotemonitoring -r dotnet --release 1.0.0-preview.2`
`pcs -t remotemonitoring -r dotnet --release 1.0.0`
`pcs -t remotemonitoring -r dotnet --release 1.1.0`
etc.

**Comment by ppathan** [comment]
Fixed
