### ISSUE TITLE
Improve `simulate.sh` logic

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-cli#175]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 

The script is coupled to an "Alive" string returned by the /status endpoint, which might change in future. The script could be more resilient to changes if, for example, it checked only for the status code.

**Comment by ppathan** [comment]
@dluc Do you still need this for simulation? Otherwise i'll close it.

**Comment by asdonald** [comment]
@dluc Closing. Please re-open if this is still a requirement.
