### ISSUE TITLE
Standard deployment broken

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-cli#183]
# Type of issue 

- [x ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
C:\source\PCS2\pcs-cli>pcs -t remotemonitoring -s standard
? Enter a solution name: ...
? Select a subscription: ...
? Select a location: East US
? Enter prefix for .azurewebsites.net: ...
? Enter a user name for the virtual machine: ...
? Enter path to SSH key file path: C:\Users\...\.ssh\...
✓ Application registered: https://portal.azure.com/microsoft.onmicrosoft.com...
✓ Created resource group: https://portal.azure.com/...
✓ Provisioning State: Succeeded Resource Type: Microsoft.DocumentDb/databaseAccounts
✓ Provisioning State: Succeeded Resource Type: Microsoft.Devices/Iothubs/Iothubkeys
✓ Provisioning State: Succeeded Resource Type: Microsoft.Web/sites/sourcecontrols
✓ Provisioning State: Succeeded Resource Type: Microsoft.Storage/storageAccounts
✓ Provisioning State: Succeeded Resource Type: Microsoft.Web/sites
✓ Provisioning State: Succeeded Resource Type: Microsoft.Web/serverfarms
✓ Provisioning State: Succeeded Resource Type: Microsoft.ContainerService/containerServices
✓ Provisioning State: Succeeded Resource Type: Microsoft.Devices/Iothubs
✓ Provisioning State: Succeeded Resource Type: Microsoft.Network/publicIPAddresses
✓ Deployed successfully, time taken: 8 minutes & 10 seconds
✕ Error: ENOENT: no such file or directory, open 'C:\Users\timlav\.kube\config-...-cluster'

**Comment by dluc** [comment]
@timlaverty were you running pcs from nodejs repo or compiled and **linked** from source code?

**Comment by timlaverty** [comment]
I was running from the CLI repo; e.g. npm install/start/link, then pcs login, then pcs -t remotemonitoring -s standard.

**Comment by dluc** [comment]
I tried to reproduce the issue but by Windows environment is probably not setup correctly, the deployment fails earlier than that, without error message (see other issue opened).

Given the error message, I'm thinking it might be an issue of missing folder or non-writable path, or maybe an old version of az/kubectl.  In any case, looks like we need to improve the "prerequisites check" before starting the deployment.

**Comment by dluc** [comment]
@ppathan did we find the root cause? I'd like to close the ticket with some sort of resolution notes

**Comment by ppathan** [comment]
Sorry I was trying to comment and mistakenly closed the issue. But, yes i have root caused the issue and will send out PR shortly.
