### ISSUE TITLE
Standard deployment stops without providing error message

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-cli#185]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

Running on a Windows machine that most probably doesn't have all the dependencies:

1. `npm install`: OK
2. `npm start build`: OK
3. `npm link`: OK
4. `pcs -t remotemonitoring -s standard`: FAIL

```
>pcs -t remotemonitoring -s standard
? Enter a solution name: deviswinstandard
? Select a subscription: ...
? Select a location: West US
? Enter prefix for .azurewebsites.net: deviswinstandard
? Enter a user name for the virtual machine: devis
? Enter path to SSH key file path: C:\Users\...\.ssh\id_rsa.pub
✓ Application registered: https://portal.azure.com/microsoft.onmicrosoft.com#blade/Microsoft_AAD_IAM/ApplicationBlade/objectId/.../appId/...
```

this is all the output I got and then the console goes back to prompt, i.e. the script dies without any error message

**Comment by dluc** [comment]
I retried with a different subscription, same behavior. The process stops immediately after registering the application.

**Comment by ppathan** [comment]
done.
