### ISSUE TITLE
Java deployments use dotnet hubmanager

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-cli#195]
# Type of issue 

- [x ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Right now Java deployments use the dotnet hubmanager microservice.  This is because of pending bugs:
		a. Continuation Token: https://github.com/Azure/azure-iot-sdk-java/issues/145
		b. Device Twin parsing of nested objects: https://github.com/Azure/azure-iot-sdk-java/issues/134, https://github.com/Azure/azure-iot-sdk-java/issues/158
		c. Null device id should be allowed for DeviceTwinDevice object when scheduling twin job 
			https://github.com/Azure/azure-iot-sdk-java/issues/159 

We need to change the hubmanager back to java for java deployments once these fixes are integrated and tested in the java hubmanager.

**Comment by ppathan** [comment]
Fixed
