### ISSUE TITLE
Hang at VMExtensions docker install

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-cli#196]
# Type of issue 

- [x ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
A deployment hung at the vmextensions/docker install execution step from a CLI, Basic, dotnet deployment:
```...
✓ Provisioning State: Succeeded Resource Type: Microsoft.Network/publicIPAddresses
✓ Provisioning State: Succeeded Resource Type: Microsoft.Network/virtualNetworks
- Provisioning State: Running   Resource Type: Microsoft.Compute/virtualMachines/extensions
- Deployed resources 12 of 13
```
I see this intermittently... could be a transient issue w/ VMs or docker.

**Comment by ppathan** [comment]
fixed
