### ISSUE TITLE
Add a Network Security Group to the network interface

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-cli#200]
# Type of issue 

- [ ] Bug
- [x] New feature
- [ ] Enhancement

# Description 

All deployments should contain a Network Security Group and the NSG should be linked to the Network Interface Controller (NIC), so that access to the Virtual Machines can be restricted to trusted networks.

The current Basic deployment has a NSG not linked to the NIC, so for instance it's not possible to restrict traffic to the SSH port.

**Comment by ppathan** [comment]
Fixed
