### ISSUE TITLE
✕ Error: ENOENT: no such file or directory, open '/Users/xyz/remotemonitoring/scripts/individual/deployment-configmap.yaml'

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-cli#206]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

When running PCS from a folder outside of the source code, the error occurs after the deployment is complete

![image](https://user-images.githubusercontent.com/371009/32291330-f39df734-bef9-11e7-817f-8db257fc059e.png)

**Comment by ppathan** [comment]
Fixed
