### ISSUE TITLE
VM provisioning failing for East US, Southeast Asia, West US

### ISSUE THREAD

**Issue by vitoc** [Azure/pcs-cli#227]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

I used to be able to provision to Southeast Asia fine. 

Updating pcs-cli to 1.0.1-preview.2 today, VM provisioning keep failing. I tried East US, Southeast Asia and West US without success.

Maybe VM size? Related: https://github.com/Azure/pcs-cli/issues/203

# Steps to reproduce 

Run:

```
pcs -t remotemonitoring -s basic
```
With version 1.0.1-preview.2 (latest version as of today).

# Expected behavior 

VM provisioning to be successful

# Current behavior 

![vm_provisioning_failing](https://user-images.githubusercontent.com/558813/32885377-4ca7cc38-caf8-11e7-8c55-45949522cf35.PNG)

# Context and Environment
* Operating System: Windows 10 Enterprise 1709
* GitHub branch: Master (https://github.com/Azure/pcs-cli)
* Node.js Runtime: v8.7.0

**Comment by vitoc** [comment]
This seems to be OK now, trying again today with East US. But I do remember VM provisioning failure once in a while. Seems like an intermittent issue (maybe due to timeout?). In any case, will be nice to have more detailed failure indications. Makes it easier to report or resolve as well. Currently, it seems like only successful deployment yields an output.json? Not exactly a log, but please do help advise me if I am wrong.

<img width="327" alt="workingdeployment" src="https://user-images.githubusercontent.com/558813/33115846-7491d078-cf9d-11e7-9368-3a65f73f41f3.PNG">

**Comment by ppathan** [comment]
fixed
