### ISSUE TITLE
Bug - PCS login failed with bug in publish/index.js

### ISSUE THREAD

**Issue by faister** [Azure/pcs-cli#231]
# Type of issue 

- [X ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Bug - PCS login failed with bug in publish/index.js

# Steps to reproduce 

1. pcs login

# Expected behavior 
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code HCRFFUY8P to authenticate.
Successfully logged in

# Current behavior 
/home/docker/pcs-cli/publish/index.js:165
                    .then(({ appId, domainName, objectId, servicePrincipalSecret }) => {
                           ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

# Known workarounds 
N/A

# Possible solution 
Remove { and } in line 165 of publish/index.js so that it becomes the following:
.then(( appId, domainName, objectId, servicePrincipalSecret ) => {

# Context and Environment
* Operating System: Linux Ubuntu
* GitHub branch: Main
* Node.js Runtime: v4.2.6

**Comment by ppathan** [comment]
fixed
