### ISSUE TITLE
Error on npm start - Cannot find module 'azure-arm-authorization',  Cannot find module 'azure-arm-compute'.

### ISSUE THREAD

**Issue by avanikp** [Azure/pcs-cli#232]
# Type of issue 

- [ X] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
While deploying basic cli .net configuration, got the following error on trying to run **npm start** -
iot-solutions@1.0.1-preview.4 build C:\Git\pcs-cli
> tsc -p tsconfig.json
src/index.ts(19,48): error TS2307: Cannot find module 'azure-arm-authorization'.
src/index.ts(20,42): error TS2307: Cannot find module 'azure-arm-compute'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! iot-solutions@1.0.1-preview.4 build: `tsc -p tsconfig.json`
npm ERR! Exit status 2
....

# Steps to reproduce 
Install basic cli .net configuration on a new machine. Follow the steps from https://github.com/Azure/pcs-cli.

# Expected behavior 
packages azure-arm-authorization and azure-arm-compute should be installed as a part of npm install

# Current behavior 
packages azure-arm-authorization and azure-arm-compute had to be installed manually using -
npm install  azure-arm-authorization
npm install  azure-arm-compute

# Known workarounds
Install packages azure-arm-authorization and azure-arm-compute using -
npm install  azure-arm-authorization
npm install  azure-arm-compute

# Possible solution 
Update installation scripts to install these packages

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Node.js Runtime: ...

**Comment by guybartal** [comment]
+1

**Comment by ppathan** [comment]
Fix
