### ISSUE TITLE
pcs login fails with cannot find module 'adal-node'and 'azure-arm-website'

### ISSUE THREAD

**Issue by prasannapad** [Azure/pcs-cli#240]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
pcs login fails due to missing node modules.

# Steps to reproduce 
After installing the pcs-cli following instructions here https://github.com/Azure/pcs-cli/, invoke pcs login

# Expected behavior 
No errors

# Current behavior 
Install the missing modules
npm install adal-node
npm install azure-arm-website

# Possible solution 

Add these to dependencies in package.json

    "adal-node": "^0.1.26",
    "azure-arm-website": "^2.0.0-preview",

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Node.js Runtime: 

{ npm: '5.6.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.9.4',
  openssl: '1.0.2n',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.50',
  zlib: '1.2.11' }

**Comment by ppathan** [comment]
Fixed
