### ISSUE TITLE
allow redeploy if previous deployment failed in the middle 

### ISSUE THREAD

**Issue by guybartal** [Azure/pcs-cli#242]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [X] Enhancement

# Description 
allow redeploy if previous deployment failed in the middle,
for example - detect that resources already deployed and proceed where it stopped before and not crash with an error that resource id is taken.
...

# Steps to reproduce 

1. start deployment 
2. stop in the middle (ctrl+c)
3. start deployment with same inputs

# Expected behavior 
the deployment will detect existing resources and continue

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Node.js Runtime: ...

**Comment by ppathan** [comment]
Fixed when moving to CIQS
