### ISSUE TITLE
Incorrect environment variable in `local` deployment

### ISSUE THREAD

**Issue by dominicbetts** [Azure/pcs-cli#248]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

If you run `pcs -s local` then the `PCS_IOTHUBREACT_HUB_ENDPOINT` has an incorrect value.
The current output looks like:

```
PCS_IOTHUBREACT_HUB_ENDPOINT=Endpoint=sb://iothub...
```

It should look like:

```
PCS_IOTHUBREACT_HUB_ENDPOINT=sb://iothub...
```

This causes the telemetry agent to fail.

**Comment by avanikp** [comment]
This issue is addressed in PR: https://github.com/Azure/telemetry-agent-dotnet/pull/31

**Comment by ppathan** [comment]
This is fixed.
