### ISSUE TITLE
Update VM settings to allow 60k TCP connections

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-cli#249]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 

The default Linux VM configuration allows only 28k TCP connections, which is a problem for simulations attempting to manage more devices.

# Known workarounds 
See the work done in this branch: https://github.com/Azure/pcs-cli/tree/dluc-simple e.g. https://github.com/Azure/pcs-cli/blob/dluc-simple/solutions/devicesimulation/single-vm/setup.sh

**Comment by ppathan** [comment]
@dluc Do you still need this?
