### ISSUE TITLE
Allow use of pre-existing service principal

### ISSUE THREAD

**Issue by Teodelas** [Azure/pcs-cli#252]
- [ ] Bug
- [ ] New feature
- [X] Enhancement

# Description 
Provide the option to use a pre-existing service principal.  This will allow PCS to be deployed in environments where the end user does not have permissions to create service principals and/or assign 'owner' role to AD objects (which is a very dangerous permission).

**Comment by ppathan** [comment]
We already support that by running deployment with `pcs --servicePrincipalId someid --servicePrincipalSecret secret` Does that not work for you?

**Comment by Teodelas** [comment]
No, the commands would still create a service principal.

Teo
