### ISSUE TITLE
pcs login fails with TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by herrbpl** [Azure/pcs-cli#271]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
When trying to use pcs login, script fails with error:
```javascript
PS C:\Users\siim\AppData\Roaming\npm> pcs login
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CMNL6EZG7 to authenticate.
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:132:11)
    at Object.fs.mkdir (fs.js:822:14)
    at ms_rest_azure_1.interactiveLoginWithAuthResponse.then (C:\Users\siim\AppData\Roaming\npm\node_modules\iot-solutions\publish\index.js:259:16)
    at process._tickCallback (internal/process/next_tick.js:178:7)
```
...

# Steps to reproduce 

1. [First step]
install iot-solutions as described in
https://docs.microsoft.com/en-gb/azure/iot-suite/iot-suite-remote-monitoring-deploy-local

2. [Second step]
run pcs login

# Expected behavior 
Subscription selection screen I guess

# Current behavior 
```javascript
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:132:11)
    at Object.fs.mkdir (fs.js:822:14)
    at ms_rest_azure_1.interactiveLoginWithAuthResponse.then (C:\Users\siim\AppData\Roaming\npm\node_modules\iot-solutions\publish\index.js:259:16)
    at process._tickCallback (internal/process/next_tick.js:178:7)
```
# Known workarounds 
Manually create folder **.pcs** in **c:\users\<yourusername>**

# Possible solution 

# Context and Environment
* Operating System: Windows 10 
* GitHub branch: commit 5ee1f7410e5471a086061d15321b8e2dceb02cfa (HEAD -> 1.0.0-preview.5-br, tag: 1.0.0-preview.5)
* Node.js Runtime: v10.0.0

**Comment by Bachkippe** [comment]
This bug also affects Mac OS:

## Context and Environment

- Operation System: macOS High Sierra 10.13.4 
- PCS version: 1.0.1 (installed from npm repository)
- Node.js Runtime: v10.0.0

## Workaround
Creating a .pcs folder in the home directory:
`mkdir .pcs`

Then calling `pcs login` again -> works.

**Comment by andrejpk** [comment]
Tracing though the code, it appears that it's erroring in this block of code creating the .pcf directory under the user profile.

```
 return ms_rest_azure_1.interactiveLoginWithAuthResponse(loginOptions).then((response) => {
        const credentials = response.credentials;
        if (!fs.existsSync(pcsTmpDir)) {
            **fs.mkdir(pcsTmpDir);**
        }
        const data = {
            credentials,
            linkedSubscriptions: response.subscriptions
        };
        fs.writeFileSync(cacheFilePath, JSON.stringify(data));
        console.log(`${chalk.green('Successfully logged in')}`);
    })
```

This fs.mkdir needs to be changed to a fs.mkdirSync. I'll post a pull request on this if I don't see one elsewhere.

**Comment by andrejpk** [comment]
It looks like this is fixed in the master branch on this commit: https://github.com/Azure/pcs-cli/commit/57d32bdbe37ff35e7d6c930e99a14347d59bd0de 

The current version on npm is just a bit older than this commit. I recommend installing this from Github.

@ppathan, is there a schedule to update the NPM distribution soon to avoid this problem? It seems like a common issue. If there is other code in flight in Github that's blocking an update to NPM, I can submit a clean pull request that just fixes this bug without all of the other code in the commit.

**Comment by ppathan** [comment]
npm package was update with this fix.
