### ISSUE TITLE
PCS standard deploy not work

### ISSUE THREAD

**Issue by SLdragon** [Azure/pcs-cli#287]
Hi, team,
I use these command to deploy standard pcs:

pcs login
pcs -t remotemonitoring -s standard 

> ? Enter a solution name: pcs-rentu-deploy-rentu
> ? Select a subscription: VSChina IoT DevINT with TTL = 7 Days
> ? Select a location: West US
> ? Enter prefix for .azurewebsites.net: pcs-rentu-deploy-rentu
> ? Enter a user name for the virtual machine: turenlong
> ? Enter path to SSH key file path: C:\Users\rentu\.ssh\id_rsa.pub
> ✓ Application registered: https://portal.azure.com/microsoft.onmicrosoft.com#blade/Microsoft_AAD_IAM/ApplicationBlade/objectId/eaf8d7df-b6a4-449d-8595-1e100eac6bbd/appId/503bfae9-e161-4eb2-b91d-7fdad7b949dc
> | Creating resource groupResources are being deployed at https://portal.azure.com/microsoft.onmicrosoft.com#resource/subscriptions/faab228d-df7a-4086-991e-e81c4659d41a/resourceGroups/pcs-rentu-deploy-rentu
> ✓ Created resource group: https://portal.azure.com/microsoft.onmicrosoft.com#resource/subscriptions/faab228d-df7a-4086-991e-e81c4659d41a/resourceGroups/pcs-rentu-deploy-rentu
> ✓ Provisioning State: Succeeded Resource Type: Microsoft.Storage/storageAccounts
> ✓ Provisioning State: Succeeded Resource Type: Microsoft.Storage/storageAccounts
> ...
> ...
> ...
> ✓ Provisioning State: Succeeded Resource Type: Microsoft.EventHub/namespaces
> ✓ Deployed successfully, time taken: 10 minutes & 23 seconds
> / Downloading credentials to setup Kubernetes from: pcs-rentu-deploy-rentu-mgmt.westus.cloudapp.azure.com 

The deployment is successful, however, I can not access the Remote Monitoring portal, I always get 

> An error occurred while sending the request. - The operation timed out

I try to run 

kubectl proxy

and when I browser http://127.0.0.1:8001/ui,
I got error messages below:
```json
{
  kind: "Status",
  apiVersion: "v1",
  metadata: { },
  status: "Failure",
  message: "no endpoints available for service "kubernetes-dashboard"",
  reason: "ServiceUnavailable",
  code: 503
}
```

I also try to login to the master Virtual Machine and run the command 

kubectl get pods -a

it shows

> 2018-05-07 09:19:07.224794 I | proto: duplicate proto type registered: google.protobuf.Any
> 2018-05-07 09:19:07.224861 I | proto: duplicate proto type registered: google.protobuf.Duration
> 2018-05-07 09:19:07.224881 I | proto: duplicate proto type registered: google.protobuf.Timestamp
> No resources found.

Any ideas about what's wrong with it? Are there some ways to trouble shoot?

Thanks

**Comment by ppathan** [comment]
From the screen it looks like it failed to download the credentials in your {username}/.kube folder. After downloading the credentials cli needs extra setup to before webapp can work. That's why you the kubectl proxy command is failing. We will look into this issue.

**Comment by SLdragon** [comment]
Hi, @ppathan, thanks for your quickly reply.
Are there some ways to manually downloading the credentials and trigger the extra setup?

**Comment by faister** [comment]
i had the same issue, desperately need to deploy it for a customer
@ppathan is there a fix to this issue yet?

**Comment by zhang-hua** [comment]
@SLdragon , @faister , if CLI failed to download the config file from Kubernetes cluster, you can manually downloaded it from the cluster master VM. Go to the portal and find the DNS name of the k8s master node with name prefixed with `k8s-master` in the deployed resource group. 
```
ssh username@master-node-dns
cat ~/.kube/config
```
or directly use scp to download the config file from the VM. Make sure your network security group allow inbound SSH traffic:
```
scp username@master-node-dns:~/.kube/config ~/.kube/config
```
After that, retry `kubectl proxy` and see if k8 dashboard is accessible.

**Comment by ppathan** [comment]
Let us know if this is still an issue. Should be fixed.
