### ISSUE TITLE
Error: "env: node\r: No such file or directory" running the command `pcs` with fresh install

### ISSUE THREAD

**Issue by sethreidnz** [Azure/pcs-cli#298]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description

New installation (on MacOS High Sierra) of the tool as per the documentation and I get the error: `env: node\r: No such file or directory` running the command `pcs`.

# Steps to reproduce 

1. Fresh install (on MacOS High Sierra) with `npm install iot-solutions -g`
2. Run the command `pcs

# Expected behavior

The tool to work without error

# Current behavior 

Gives me the error `env: node\r: No such file or directory`

# Environment Information

Node:

```
v8.2.1
```

MacOS High Sierra:

![screen shot 2018-06-18 at 1 40 31 pm](https://user-images.githubusercontent.com/4713713/41514764-a3649b66-72fd-11e8-8df1-e28731bd4a73.png)

**Comment by ppathan** [comment]
Let us know if still an issue.

**Comment by alicejgibbons** [comment]
This is still an issue in WSL 2
