### ISSUE TITLE
Switch ARM Template to use AKS

### ISSUE THREAD

**Issue by jwendl** [Azure/pcs-cli#299]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [X] Enhancement

# Description
Let's move PCS CLI to AKS instead of ACS

# Steps to reproduce 
N/A

# Expected behavior
We deploy an AKS cluster instead of an ACS one

# Current behavior
Currently PCS -t standard creates an ACS cluster that has to be managed

# Known workarounds 
N/A

# Possible solution 
Will submit pull request shortly.

# Context and Environment

**Comment by zhang-hua** [comment]
Close it since this work has been done.
