### ISSUE TITLE
Unable to deploy Docker images through Kubernetes using .yaml files

### ISSUE THREAD

**Issue by faister** [Azure/pcs-cli#301]
# Type of issue 

- [X] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Issue with deploying Docker images through Kubernetes using .yaml files in remotemonitoring/scripts
Error: invalid type for io.k8s.kubernetes.pkg.api.v1.ServiceSpec.loadBalancerIP

# Steps to reproduce 

1. Follow instructions at https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/wiki/Developer-Reference-Guide#deploy-docker-images-through-kubernetes
2. kubectl create -f ./remotemonitoring/scripts/nginx-ingress-controller.yaml
3. Similar issue with running kubectl create -f ./remotemonitoring/scripts/all-in-one.yaml

# Current behavior 
azureuser@vm-h4c37:~/pcs-cli/solutions/remotemonitoring/scripts$ kubectl create -f nginx-ingress-controller.yaml
service "default-http-backend" created
replicationcontroller "default-http-backend" created
error: error validating "nginx-ingress-controller.yaml": error validating data: ValidationError(Service.spec.loadBalancerIP): invalid type for io.k8s.kubernetes.pkg.api.v1.ServiceSpec.loadBalancerIP: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false

azureuser@vm-h4c37:~/pcs-cli/solutions/remotemonitoring/scripts$ kubectl create -f nginx-ingress-controller.yaml --validate=false
deployment.extensions "nginx-ingress-controller" created
Error from server (AlreadyExists): error when creating "nginx-ingress-controller.yaml": services "default-http-backend" already exists
Error from server (AlreadyExists): error when creating "nginx-ingress-controller.yaml": replicationcontrollers "default-http-backend" already exists
Error from server (BadRequest): error when creating "nginx-ingress-controller.yaml": Service in version "v1" cannot be handled as a Service: [pos 120]: json: expect char '"' but got char '{'

azureuser@vm-h4c37:~/azure-iot-pcs-remote-monitoring-dotnet/cli/solutions$ kubectl create -f ./remotemonitoring/scripts/all-in-one.yaml
ingress.extensions "remotemonitoring" created
error: error validating "./remotemonitoring/scripts/all-in-one.yaml": error validating data: ValidationError(Service.spec.loadBalancerIP): invalid type for io.k8s.kubernetes.pkg.api.v1.ServiceSpec.loadBalancerIP: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false

# Context and Environment
* Operating System: Linux and Windows
* GitHub branch: Current
* Node.js Runtime: v8.11.3

**Comment by zhang-hua** [comment]
@faister: Have you replaced "{xxx}" in the yaml file with the  actual values of the ConfigMap section?
