### ISSUE TITLE
Move Remote Monitoring configuration files to the Remote Monitoring repo

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-cli#32]
# Type of issue
- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description
Currently, the remote monitoring configuration files are stored in this repo [here](https://github.com/Azure/pcs-cli/tree/master/remotemonitoring) however we should move the files, have one copy in the [.NET solution](https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet) and one in the [Java solution](https://github.com/Azure/azure-iot-pcs-remote-monitoring-java).

The files should probably be organized by orchestrator, e.g. 
* /deployment/kubernetes
* /deployment/docker
* etc.

Once we add other solutions, this approach will also help developing solutions independently.

**Comment by ppathan** [comment]
will fixed with move to CIQS
