### ISSUE TITLE
Solution deployment for DS should use release version

### ISSUE THREAD

**Issue by ppathan** [Azure/pcs-cli#337]
# Type of issue 

- [x] Bug
- [x] New feature
- [ ] Enhancement

# Description 
Currently the Device simulation and standard deployments for RM uses hard coded version of **master** for [reverse-proxy-dotnet](https://github.com/Azure/reverse-proxy-dotnet). We should make variable take in release version similar to the basic template to avoid accidentally releasing a version from master branch.

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Node.js Runtime: ...

**Comment by ppathan** [comment]
@maple10001 Any update on this?

**Comment by asdonald** [comment]
@avanikp Any update on this?

**Comment by asdonald** [comment]
@avanikp Do you have any update on this?

**Comment by asdonald** [comment]
RM is done. DS is outstanding.
