### ISSUE TITLE
Remote Monitoring solution accelerator Standard location(only US or Europe?)

### ISSUE THREAD

**Issue by tai000** [Azure/pcs-cli#349]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 

 I deployed the Remote Monitoring Solution Acceralator using  the CLI command  below
in this command.

pcs -t remotemonitoring -s standard -r java

location select is only US or Europe. In other way, Can I select other country?

...

# Steps to reproduce 

1. [First step]
pcs -t remotemonitoring -s standard -r java
2. [Second step]
set other setting 

3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Node.js Runtime: ...

**Comment by asdonald** [comment]
@tai000 This is based on your subscription and resource availability.
