### ISSUE TITLE
Local Deploy error code

### ISSUE THREAD

**Issue by tai000** [Azure/pcs-cli#350]
# Type of issue 

- [x] Bug
- [ ] New feature
- [x] Enhancement

# Description 
I use this tutorial 
https://docs.microsoft.com/ja-jp/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local

in Run a local deployment section,
i use the command below on Windows PowerShell.
pcs -s local

but it returned error code
do you know the solution?
/////////////////////////////////////////////////////////////////////////////////////////////////////////
✓ Created resource group: https://portal.azure.com/xxxxxxxxxxxxx/resourceGroups/testxxxx
✓ Provisioning State: Succeeded        Resource Type: Microsoft.Devices/Iothubs/Iothubkeys
✓ Provisioning State: Succeeded        Resource Type: Microsoft.TimeSeriesInsights/environments
✕ Deployment failed
{
  "code": "Conflict",
  "message": "The Stream Analytics job is not in a valid state to perform this operation.",
  "details": {
    "code": "409",
    "message": "The Stream Analytics job is not in a valid state to perform this operation.",
    "correlationId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "requestId": "xxxxxxxxxxxxxxxxxxxxxx"
  }
}
/////////////////////////////////////////////////////////////////////////////////////////////////////////
※ xxx... : partly I replaced.

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Node.js Runtime: ...

**Comment by zhang-hua** [comment]
@tai000 , can this problem be reproduced? what is the error message saying in the deployment result on Azure Portal?

**Comment by asdonald** [comment]
@tai000 Closing this issue for no response. Please re-open this if you are still seeing issues.
