### ISSUE TITLE
Service principal login issues

### ISSUE THREAD

**Issue by ppathan** [Azure/pcs-cli#360]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

* Tried login with service principal that takes to regular login
* Code that creates resouce management client for TSI locations is not taking into consideration the service principal login
* Method createAppRole fails with Odata error which is returned promise completion.
* Was not able to verify this getPatchedDeviceTokenCredentials since service principal login is not working.

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Node.js Runtime: ...

**Comment by asdonald** [comment]
@jillcary Please look into this issue.

**Comment by asdonald** [comment]
@zhang-hua @jillcary Can you look into this for Oct.

**Comment by asdonald** [comment]
@zhang-hua by end of Oct.

**Comment by asdonald** [comment]
@zhang-hua Early Nov target date.

**Comment by ppathan** [comment]
Fixed by #430
