### ISSUE TITLE
PCS-CLI should save the environment variables in a .env file and provide the pointer to the user

### ISSUE THREAD

**Issue by avneet723** [Azure/pcs-cli#401]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 
PCS CLI currently asks the user to save the environment variables under \scripts\local\.env file; however, we never read this file for the current or future deployments. We should replace this step with just creating a backup file with all the environment variables and pointing the user to it as a reference. 
...

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Node.js Runtime: ...

**Comment by zhang-hua** [comment]
Just submitted a PR for this enhancement: https://github.com/Azure/pcs-cli/pull/402

**Comment by asdonald** [comment]
@avneet723  to update once completed.

**Comment by avneet723** [comment]
This issue has been resolved with the following PR: 
https://github.com/Azure/pcs-cli/pull/402
