### ISSUE TITLE
Don't output commands with credentials from setup.sh script to console

### ISSUE THREAD

**Issue by zadixon** [Azure/pcs-cli#406]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Don't output commands with credentials from setup.sh script to console.
When the vm extension deployment fails, these are logged, meaning that secrets can be exposed.

# Steps to reproduce 

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Node.js Runtime: ...

**Comment by zhang-hua** [comment]
The error message was saved into: /var/lib/waagent/custom-script/download/1/stderr

**Comment by asdonald** [comment]
#408 Need to do the same here.

**Comment by zhang-hua** [comment]
PR https://github.com/Azure/pcs-cli/pull/427 pushed by @ sakimsft to fix this issue.

**Comment by zhang-hua** [comment]
Close it since PR has been merged.
