### ISSUE TITLE
Remote monitoring services failed running due to missing environment variables.

### ISSUE THREAD

**Issue by sakimsft** [Azure/pcs-cli#440]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Deploy all Microservices by following below instruction.
https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local

Two services failed to start because of missing environment variable. 
If I set environment variable manually, services were running without an error.

# Steps to reproduce 

1. Follow instruction: https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local
2. Run all microservices from visual studio 2017

# Expected behavior 
all services running

# Current behavior 
Set all environment variables manually.

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Node.js Runtime: ...

**Comment by klabrunda** [comment]
I’m seeing the same problem when trying to deploy locally, either through VS 2017 or Docker following the Microsoft docs. It looks like it fails on the database connection. Also can’t start the 
Stream Analytics Job through the Azure Portal as that fails in the database connection. What is the workaround? How do you set the environment variables manually?

**Comment by sakimsft** [comment]
the fix merged to master.
https://github.com/Azure/pcs-cli/commit/e9f7ee86b3dcf9e1f4d0ffeb51090ef54ea38a76
