### ISSUE TITLE
Command arguments is still required to provide in questions even provided by user

### ISSUE THREAD

**Issue by zhang-hua** [Azure/pcs-cli#444]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

The arguments like `solutionName`, `domainId`, `subscriptionId` is still required in the question even if they are provided in the command line.

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
pcs --solutionName yourSolutionName --subscriptionId yourSubscriptionId --domainId yourDomainId

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Node.js Runtime: ...

**Comment by ppathan** [comment]
Fixed
