### ISSUE TITLE
Subscription ID not found in cache

### ISSUE THREAD

**Issue by gauravagerwala** [Azure/pcs-cli#466]
# Type of issue 

- [x ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
While trying to create a standard deployment using service principals it throws the following error : 
```
Selected subscriptionId was not found in cache
Error: Selected subscriptionId was not found in cache
    at subPrompt.then (/home/learning/pcs-cli/publish/index.js:182:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

...

# Steps to reproduce 

1. `pcs -t remotemonitoring -s standard --servicePrincipalId {servicePrincipalId} --servicePrincipalSecret {servicePrincipalSecret}`

# Context and Environment
* Operating System: ... Ubuntu 16.04
* GitHub branch: ... Checked with 2.1.3 and master

**Comment by ppathan** [comment]
@elvinm Can you look at this?

**Comment by elvinm** [comment]
ServicePrinicipalId and secret are used to do a non interactive deployment. In this scenario it is expected that the user has provided additional details. In this case you would need to use at least a command of the form:

--servicePrincipalId xxxx --servicePrincipalSecret xxxx --domainId xxxx --subscriptionId xxxx

The error logic handling should be cleaned up here to verify that all the parameters were provided so that it leads to a less confusing error message.

**Comment by jasonb815** [comment]
even with all of the above information included I am getting this :  

Successfully logged in
Selected subscriptionId was not found in cache
Error: Selected subscriptionId was not found in cache
    at subPrompt.then (/home/mqadmin/pcs-cli/publish/index.js:189:35)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

**Comment by jasonb815** [comment]
@elvinm Any idea what's going on here and causing this?

**Comment by elvinm** [comment]
Are you perhaps using an older version of the CLI? What version is it (pcs --version)?

**Comment by jasonb815** [comment]
pcs --version
2.2.1

**Comment by jasonb815** [comment]
@elvinm @ppathan Any help here?  This is still a problem...

**Comment by ppathan** [comment]
@jasonb815 Sometimes I have seen this error show up when 2-factor auth has been enabled by the tenant/subscription. Do you have 2-factor auth enabled for your account?

**Comment by jasonb815** [comment]
yes, but we have created a service principal account to use during automated deployment of PCS and ther AZ services.  It works fine with the AZ CLI, but gets this error with the PCS CLI.  ??
