### ISSUE TITLE
local deployment failed

### ISSUE THREAD

**Issue by sakimsft** [Azure/pcs-cli#492]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
cli was running and waiting "registering application in the azure active directory" and never finished.

# Steps to reproduce 

1. deploy cli locally with below command.
pcs -t remotemonitoring -s local -r java --dockerTagOverride keyvaultintgr --versionOverride keyvault-br-3-test

2. There was an error while registering application
? Enter a solution name: saki-bugbash-kv
? Select a subscription: iotc-flashmagnus-sublib-002
? Select a location: West US
| Registering application in the Azure Active DirectoryError: Could not create new application in this tenant: The password must contain at least 1 special character. paramName: PasswordCredentials, paramValue: , objectType: Microsoft.Online.DirectoryServices.Application
    at graphClient.applications.create.then.catch (c:\saki\temp\bugbash\pcs-cli\publish\index.js:496:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

# Expected behavior 
Deploy CLI successfully

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Node.js Runtime: ...

**Comment by ppathan** [comment]
Fixed
