### ISSUE TITLE
SDS Deployment for Java wasn't not able to start streaming job

### ISSUE THREAD

**Issue by ppathan** [Azure/pcs-cli#493]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Streaming job didn't start for Java deployment because DocDb collections were not present

# Steps to reproduce 

1. Deploy through SDS for Java. https://sds.azureiotsolutions.com/en-US/Deployments/details/5cff90a9-757b-4ef1-896e-56ad97166bba@c1ea7484-ece6-4678-b97b-29bf6bb99d05

**Comment by elvinm** [comment]
This is fixed. https://sds.azureiotsolutions.com/en-US/Deployments/details/f5ae113c-73d3-4a83-ac43-377d7a83f10e@c1ea7484-ece6-4678-b97b-29bf6bb99d05 

It was using the wrong branch for testing Java
