### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by deepakagra** [Azure/pcs-cli#499]
# Type of issue 

- [ x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
While trying to build this project; Installation is failing.
...

# Steps to reproduce 

1. [after cloning the repo; npm install worked fine]
2. [npm start gave errors]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ... Windows 10 Pro
* GitHub branch: ... main
* Node.js Runtime: ... 6.10.2
[Build-failing.txt](https://github.com/Azure/pcs-cli/files/3050487/Build-failing.txt)

**Comment by deepakagra** [comment]
Even after updating node to latest version; issue remains. 
[2019-04-07T02_15_05_909Z-debug.log](https://github.com/Azure/pcs-cli/files/3051125/2019-04-07T02_15_05_909Z-debug.log)

**Comment by elvinm** [comment]
We have a newer version out with quite a bit of changes. It would be good to try to update (git pull, npm install, npm start). If there are errors still copying the updated logs.

**Comment by deepakagra** [comment]
With current code changes; it works fine now .. Thanks
