### ISSUE TITLE
Problems deploying Remote Monitoring via the CLI

### ISSUE THREAD

**Issue by jenniferburch** [Azure/pcs-cli#503]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

Deployment of remote monitoring solution from source CLI is not producing a usable Remote Monitoring Solution

# Steps to reproduce 

1. npm install -g iot-solutions
2. pcs login
3. pcs -t remotemonitoring -s basic -r dotnet
4. Answer prompts, create DEP1  (this deployment works as expected)
3. Forked https://github.com/Azure/pcs-cli to another repo and clone
4. cd to the root folder
5. npm install
6. npm start
7. npm link
8. pcs login 
9. pcs -t remotemonitoring -s basic -r dotnet
10. Answer prompts, create DEP2, use same values as DEP1 except for solution name

# Expected behavior 
Be able to launch the Remote Monitoring website

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: Win 10 Pro
* GitHub branch: master
* Node.js Runtime: 10.15.3

**Comment by ppathan** [comment]
@elvinm This is because of code in master default is pointing to a branch which isn't ready for release. Once we do the release this should be fixed automatically.

**Comment by jenniferburch** [comment]
Thanks @ppathan, so what branch represents the current release?  Do you have an ETA on the next release?

**Comment by elvinm** [comment]
The latest release is out. The current (3.0.1) CLI release is now producing proper deployments.
