### ISSUE TITLE
Deployment of Remote Monitoring Standard failed

### ISSUE THREAD

**Issue by dhermyt** [Azure/pcs-cli#504]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

Deployment fails with the error below.

# Steps to reproduce 

pcs -t remotemonitoring -s standard

# Expected behavior 
...

# Current behavior 
`✕ Deployment validation failed:
{
  "code": "InvalidTemplateDeployment",
  "message": "The template deployment 'deployment-danielmon5' is not valid according to the validation procedure. The tracking id is '8c5f46ef-9623-4ad5-bda8-a5af7c5268ba'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.",
  "details": [
    {
      "code": "InvalidParameter",
      "message": "Provisioning of resource(s) for container service danielmon5-cluster in resource group danielmon5 fail✕ Error: {"code":"InvalidTemplateDeployment","message":"The template deployment 'deployment-danielmon5' is not valid according to the validation procedure. The tracking id is '8c5f46ef-9623-4ad5-bda8-a5af7c5268ba'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.","details":[{"code":"InvalidParameter","message":"Provisioning of resource(s) for container service danielmon5-cluster in resource group danielmon5 failed. Message: {\n  \"code\": \"InvalidParameter\",\n  \"message\": \"The value of parameter orchestratorProfile.OrchestratorVersion is invalid.\",\n  \"target\": \"orchestratorProfile.OrchestratorVersion\"\n }. Details: "}]}`

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: Windows 10 64bit
* GitHub branch: latest
* Node.js Runtime: 10.15.3

**Comment by ppathan** [comment]
@isaac-dasan This was fixed by you, can you double check if it is just case of waiting for release. If so, close after release. Co-ordinate with @elvinm.
