### ISSUE TITLE
KeyVault Conflict When Deploying Remote Monitoring basic via the CLI 

### ISSUE THREAD

**Issue by zhshen** [Azure/pcs-cli#517]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

When I was deploying resource monitoring, the deployments of resources group raised an error.
'VM has reported a failure when processing extension 'scriptextensions''.

# Steps to reproduce 

1. npm install
2. npm start
3. npm link
4. pcs login
5. pcs
# Current behavior
For a long time, the deployment stopped and show an error message:

_At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details._

I checked the deployment log in resource group. I found the keyvault deployment showed an exception when it was trying to deploy the vm-xxxx/scriptextensions :

_"statusCode": "**Conflict**", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionProvisioningError", "message": "**VM has reported a failure when processing extension 'scriptextensions'**. Error message: \"Enable failed: failed to execute command: command terminated with exit status=1\n[stdout]\nExit code: 1\nSetup failed, please see log file '/app/setup.log' for more information\n\n[stderr]\n\"." } ] } },_.
# Expected behavior 

I tried East Asia and West US with difference subscriptions, this error has still been occurred.

# Known workarounds 
If I remove the **Microsoft.Compute/virtualMachines/extensions** in keyvault.json. The deployment would be continued.

# Possible solution 
...

# Context and Environment
* Operating System: Windows 10 64 bits
* GitHub branch: Latest master
* Node.js Runtime: 10.16.0

**Comment by Ashurek85** [comment]
I have the same issue.

You said that "_if I remove the Microsoft.Compute/virtualMachines/extensions in keyvault.json. The deployment would be continued._"

The system works? Can I execute extensions manually?

**Comment by zhshen** [comment]
No, The system can not work after I remove the 'Microsoft.Compute/virtualMachines/extensions'

**Comment by Ashurek85** [comment]
This is a serious problem, we need a solution

**Comment by Ashurek85** [comment]
Detail error:

![image](https://user-images.githubusercontent.com/45046196/61443572-123a5e80-a94a-11e9-91ac-b85f4d49d965.png)

**Comment by ravitola** [comment]
I am having a similar issue.    Is there a workaround or is fix underway to resolve this issue ?

**Comment by elvinm** [comment]
I am currently not seeing this issue. I was able to install with npm instlal -g iot-solutions and then deploy with pcs. The website was running right after. Do you have any further details on how you reproduced this yesterday?

**Comment by LSpencer777** [comment]
I get exactly the same error as @Ashurek85 

Microsoft, why are you apparently not paying attention to this issue? It has been open for almost a year. Users (like me) who want to evaluate your Azure IoT solution are going to get frustrated and go elsewhere.

**Comment by muralim2576** [comment]
What a pathetic way of managing things by Microsoft. This issue has been around for years, is this how Microsoft provides support for their solutions??
