### ISSUE TITLE
CLI RM standard deployment failed - SyntaxError

### ISSUE THREAD

**Issue by skylinefly** [Azure/pcs-cli#534]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
After _psc -t remotemonitoring -s standard -r dotnet_ and appointing of necessary information the deployment process hungs with SyntaxError right after Application registration.
It is always responds with "Unexpected token p in JSON at position 8642".
```
PS C:\Users\user\pcs-cli> pcs -t remotemonitoring -s standard
? Enter a solution name: name
? Select a subscription: subscription
? Select a location: North Europe
? Enter prefix for .azurewebsites.net: unicwebname
✓ Application registered: https://portal.azure.com/_changed_.onmicrosoft.com#blade/Microsoft_AAD_IAM/ApplicationBlade/objectId/d1ba0337-52cb-4a53-a016-dadf95334d2a/appId/c5fcac85-c339-4183-89d2-1bcf2f1ca291
SyntaxError: C:\Users\user\pcs-cli\publish\solutions\remotemonitoring\armtemplates\standard.json: Unexpected token p in JSON at position 8642
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1192:22)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at DeploymentManager.submit (C:\Users\user\pcs-cli-master\publish\deploymentmanager.js:75:30)
    at C:\Users\user\pcs-cli\publish\index.js:306:54
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
# Steps to reproduce 
All done in Power Shell
1. cd ~
2. npm install -g iot-solutions
3. git clone https://github.com/Azure/pcs-cli.git
4. cd pcs-cli
5. npm install
6. npm start
7. npm link /* could be ommited */
8. Sign in using _pcs login_ and credentials for an Azure account
9. run a deployment process by any of listed command:
    pcs -t remotemonitoring -s standard 
    pcs -t remotemonitoring -s standard -r dotnet
    pcs -t remotemonitoring -s standard -r java
10. described error appearing.

# Expected behavior 
Request for VM credentials and normal deployment process flow.
RM solution deployment successfully finished

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: Windows 10 x64 version 1809
* GitHub branch: https://github.com/Azure/pcs-cli
* Node.js Runtime: v12.16.1
* npm: npm@6.13.4

**Comment by skylinefly** [comment]
Same error apear under Ubuntu 18.04 LTS with Nodejs v13.9.0 and npm 6.13.7

**Comment by skylinefly** [comment]
So, **to fix the problem** described you need to make some changes in file 
_pcs-cli/publish/solutions/remotemonitoring/armtemplates/standard.json_
In 240 string there is "pcs" statment that is typo mistake. Just delete it and save the file.
After that you will able to proceed with deployment as well.
For **Linux** the file is located 
_/usr/local/lib/node_modules/iot-solutions/publish/solutions/remotemonitoring/armtemplates/standard.json_

**Comment by skylinefly** [comment]
Probably this should keep opened to fix the issue in repository.

**Comment by baranyiszabolcs** [comment]
HI
after fixing the json file another  bug occurs  deails  and how to reproduce see below
- I assume this service principal creation missing from json.
-------------------------------------------------------------------------------------------------------
C:\tmp>pcs -t remotemonitoring -s standard -r dotnet
? Enter a solution name: bszrmonky
? Select a subscription: Microsoft Azure Internal Consumption
? Select a location: North Europe
? Enter prefix for .azurewebsites.net: bszrmonky
✓ Application registered: https://portal.azure.com/microsoft.onmicrosoft.com#blade/Microsoft_AAD_IAM/ApplicationBlade/o✓ Created resource group: https://portal.azure.com/microsoft.onmicrosoft.com#resource/subscriptions/4a99ad0b-5a1c-46f4-✕ Deployment validation failed:
{
  "code": "InvalidTemplateDeployment",
  "message": "The template deployment 'deployment-bszrmonky' is not valid according to the validation procedure. The tracking id is '33d3d3d1-f0a9-4f42-81ea-4de75613bd02'. See inner errors for details.",
  "details": [
    {
      "code": "ServicePrincipalNotFound",
      "message": "Provisioning of resource(s) for container service bszrmonky-cluster in resource group bszrmonky failed. Message: {\n  \"code\": \"ServicePrincipalNotFound\",\n  \"message\": \"Service principal clientID: e9ff31a2-dd9f-41✕ Error: {"code":"InvalidTemplateDeployment","message":"The template deployment 'deployment-bszrmonky' is not valid according to the validation procedure. The tracking id is '33d3d3d1-f0a9-4f42-81ea-4de75613bd02'. See inner errors for details.","details":[{"code":"ServicePrincipalNotFound","message":"Provisioning of resource(s) for container service bszrmonky-cluster in resource group bszrmonky failed. Message: {\n  \"code\": \"ServicePrincipalNotFound\",\n  \"message\": \"Service principal clientID: e9ff31a2-dd9f-41dc-b0de-cdb32472afef not found in Active Directory tenant 72f988bf-86f1-41af-91ab-2d7cd011db47, Please see https://aka.ms/aks-sp-help for more details.\"\n }. Details: "}]}
