### ISSUE TITLE
Error while setting up RM accelerator locally

### ISSUE THREAD

**Issue by lalitkhatter** [Azure/pcs-cli#537]
# Type of issue 

- [X ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
√ Provisioning State: Succeeded Resource Type: Microsoft.EventHub/namespaces/eve
? Deployment failed
{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning stat
e 'Failed'.",
    "details": [
      {
        "code": "ServiceUnavailable",
        "message": "Sorry, we are currently experiencing high demand in this reg
ion, and cannot fulfill your request at this time. We work continuously to bring
 more and more capacity online, and encourage you to try again shortly. Please d
o not hesitate to contact us via Azure support at any time or for any reason usi
ng this link http://aka.ms/azuresupport.\r\nActivityId: 3f4e6010-b1d6-4361-9832-
e152b550bfaa, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents
.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documen
ts.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Docum
ents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Doc
uments.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.D
ocuments.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure
.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azu
re.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.A
zure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft
.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microso
ft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Micro
soft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Mic
rosoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, M
icrosoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0,
 Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.
0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.1
0.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2
.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common
/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Comm
on/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Co
mmon/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.
Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Document
s.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Docume
nts.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Docu
ments.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Do
cuments.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.
Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azur
e.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Az
ure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.
Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0"
      }
    ]
  }
}

...

# Steps to reproduce 
Run start.bat file after going through steps mentioned in https://docs.microsoft.com/en-gb/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-cli

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
successfully created resources locally and in azure

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ... 
* GitHub branch: ... latest
* Node.js Runtime: ... v12.16.1

**Comment by UweThomas** [comment]
Any news on this issue? 
I experience the same behavior with the deploy.cmd of the Industrial-IoT repository (https://github.com/Azure/Industrial-IoT). 
It stops while deploying the document database: "Resource Microsoft.DocumentDb/databaseAccounts 'documentdb-u47mvs' failed with message ..." the rest of the message is identical to the json above.
